variables:
  GIT_STRATEGY: clone

configure-build-test:
  stage: build
  script:
    - source /projects/sems/modulefiles/utils/sems-modules-init.sh
    - module load sems-gcc/10.1.0
    - module load sems-cmake/3.21.1
    - module load sems-ninja/1.10.1
    - module load sems-boost/1.69.0
    - module load sems-openmpi/1.10.7
    - module load sems-zlib/1.2.11
    - module load sems-hdf5/1.10.7
    - module load sems-yaml-cpp/0.6.2
    - module load sems-doxygen/1.8.20
    - module load sems-netcdf-c/4.7.3
    - module load sems-parallel-netcdf/1.12.1
    - module load sems-texlive/20200406
    - mkdir build
    - cd build
    - ../scripts/configure-MrHyDE/configure-MrHyDE-vaporwave-serial-runner | tee ../runner_log.txt
    - ninja | tee -a ../runner_log.txt
    - cd ../regression
    - ln -s ../build/src/mrhyde mrhyde
    - ./runtests.py | tee -a ../runner_log.txt
    - cd ..

  artifacts:
    paths:
      - runner_log.txt